apiVersion: apps/v1
kind: Deployment
metadata:
  name: merhaba-dunya-deploy
  labels:
    name: merhaba-dunya
spec:
  replicas: 1
  selector:
    matchLabels:
      name: merhaba-dunya
  template:
    metadata:
      labels:
        name: merhaba-dunya
    spec:
      containers:
      - image: techakademi/merhabadunya:1
        name: merhaba-dunya
      nodeSelector:
        gpu: "true"